// ── GYM EXERCISES (Phase 1 — shoulder-safe, lower-back-safe) ─────────────────
// home_compatible: false — require machines, cables, or significant load

export const EXERCISES = [

  // ── HINGE ──────────────────────────────────────────────
  {
    name: "Dumbbell Romanian Deadlift",
    category: "hinge",
    equipment: ["dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Hip-hinge movement. Soft knees, push hips back, keep dumbbells close to legs. Feel the stretch in hamstrings at the bottom. THE foundational longevity exercise — trains the entire posterior chain.",
    muscle_groups: ["hamstrings", "glutes", "lower_back"],
  },
  {
    name: "Hip Thrust",
    category: "hinge",
    equipment: ["bodyweight", "dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Upper back on bench, drive hips up squeezing glutes hard at the top. Hold 1 second. Best glute-isolation exercise with minimal spinal loading.",
    muscle_groups: ["glutes", "hamstrings"],
  },
  {
    name: "Good Morning",
    category: "hinge",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Hands behind head, soft knees, hinge forward from hips until you feel hamstring tension. Drive hips forward to return. Teaches the hip-hinge pattern with no equipment.",
    muscle_groups: ["hamstrings", "glutes", "lower_back"],
  },
  {
    name: "Single Leg Glute Bridge",
    category: "hinge",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Lie on back, one foot on floor, other leg extended. Drive hips up through the grounded heel, squeeze glute at top. Builds unilateral hip strength and exposes asymmetries. Each side.",
    muscle_groups: ["glutes", "hamstrings", "core"],
  },
  {
    name: "Barbell Romanian Deadlift",
    category: "hinge",
    equipment: ["barbell"],
    phase_unlock: 2,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Same hip-hinge as dumbbell RDL but with barbell. Greater loading potential. Keep bar close to legs throughout.",
    muscle_groups: ["hamstrings", "glutes", "lower_back"],
  },

  // ── SQUAT ──────────────────────────────────────────────
  {
    name: "Goblet Squat",
    category: "squat",
    equipment: ["dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Hold dumbbell at chest, feet shoulder-width, toes out slightly. Sit between knees, chest tall. The best teaching tool for the squat pattern — counterbalance keeps torso upright.",
    muscle_groups: ["quads", "glutes", "core"],
  },
  {
    name: "Bulgarian Split Squat",
    category: "squat",
    equipment: ["bodyweight", "dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Rear foot elevated on bench, front foot forward. Lower back knee toward floor with control. Research shows single-leg strength is the single best predictor of longevity outcomes. Each leg.",
    muscle_groups: ["quads", "glutes", "hamstrings"],
  },
  {
    name: "Reverse Lunge",
    category: "squat",
    equipment: ["bodyweight", "dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Step backward, lower rear knee toward floor. Less knee stress than forward lunge. Keep front shin vertical and chest tall. Each side.",
    muscle_groups: ["quads", "glutes"],
  },
  {
    name: "Step Up",
    category: "squat",
    equipment: ["bodyweight", "dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Step onto a bench or box, drive through the front heel — don't push off the back foot. Control the descent. Trains single-leg strength and real-world function. Each side.",
    muscle_groups: ["quads", "glutes"],
  },
  {
    name: "Barbell Back Squat",
    category: "squat",
    equipment: ["barbell"],
    phase_unlock: 3,
    shoulder_safe: false,
    lower_back_safe: true,
    home_compatible: false,
    description: "Bar on upper traps, brace hard, descend until thighs parallel. Requires shoulder mobility — Phase 3 only.",
    muscle_groups: ["quads", "glutes", "core"],
  },

  // ── PUSH ──────────────────────────────────────────────
  {
    name: "Dumbbell Floor Press",
    category: "push",
    equipment: ["dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Lie on floor, dumbbells at chest, press up. Floor limits shoulder extension at bottom — protects the joint. Great for learning pressing mechanics safely.",
    muscle_groups: ["chest", "triceps", "front_delts"],
  },
  {
    name: "Incline Dumbbell Press",
    category: "push",
    equipment: ["dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "30-45° incline bench. Press dumbbells from chest level, elbows at ~45° from body. Upper chest emphasis. More shoulder-friendly angle than flat pressing.",
    muscle_groups: ["upper_chest", "front_delts", "triceps"],
  },
  {
    name: "Push-Up",
    category: "push",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Hands shoulder-width, body straight line from head to heels. Lower chest to floor, press back up. The most complete upper-body bodyweight exercise. Scales infinitely — knees, standard, feet elevated, weighted vest.",
    muscle_groups: ["chest", "triceps", "front_delts", "core"],
  },
  {
    name: "Pike Push-Up",
    category: "push",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Inverted V position with hips high, head between arms. Lower crown of head toward floor and press back up. Trains the vertical push pattern and anterior deltoid without any equipment.",
    muscle_groups: ["front_delts", "triceps", "upper_chest"],
  },
  {
    name: "Barbell Bench Press",
    category: "push",
    equipment: ["barbell"],
    phase_unlock: 2,
    shoulder_safe: false,
    lower_back_safe: true,
    home_compatible: false,
    description: "Flat bench, bar to lower chest. Phase 2+ only due to shoulder demands. Requires proper arch, leg drive, and shoulder positioning.",
    muscle_groups: ["chest", "triceps", "front_delts"],
  },
  {
    name: "Landmine Press",
    category: "push",
    equipment: ["barbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "One end of a barbell anchored in a landmine (or corner). Press the free end up and forward on an arc — half-kneeling or standing. The shoulder-friendliest vertical press: the arcing path avoids the impingement zone of strict overhead pressing, so it builds overhead strength without aggravating cranky shoulders. The default vertical press for this program.",
    muscle_groups: ["front_delts", "upper_chest", "triceps", "core"],
  },
  {
    name: "Dumbbell Shoulder Press",
    category: "push",
    equipment: ["dumbbell"],
    phase_unlock: 2,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Seated, back supported, neutral or slightly-angled grip. Press dumbbells overhead without locking the shoulders up to the ears. True vertical pressing pattern — unlocked in Phase 2 once shoulder capacity is established. Stop short of any pinch; the landmine press is the regression if it bothers the shoulder.",
    muscle_groups: ["front_delts", "triceps", "upper_chest"],
  },

  // ── PULL ──────────────────────────────────────────────
  {
    name: "Chest Supported Row",
    category: "pull",
    equipment: ["dumbbell", "machine"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Lie prone on incline bench or use chest supported machine. Row dumbbells to lower ribcage, drive elbows back. Chest support eliminates lower back compensation — the safest and most honest horizontal pull.",
    muscle_groups: ["lats", "rhomboids", "biceps", "rear_delts"],
  },
  {
    name: "Seated Cable Row",
    category: "pull",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Sit tall, neutral grip, pull to lower chest with elbows tight to body. Keep torso upright — don't rock. Trains the full lat and mid-back with constant tension.",
    muscle_groups: ["lats", "rhomboids", "biceps"],
  },
  {
    name: "Machine Row",
    category: "pull",
    equipment: ["machine"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Chest on pad, neutral grip handles. Pull to chest, squeeze shoulder blades together. Machine provides stability — ideal for focusing on the back without worrying about form elsewhere.",
    muscle_groups: ["lats", "rhomboids", "biceps"],
  },
  {
    name: "Dumbbell Single Arm Row",
    category: "pull",
    equipment: ["dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Knee and hand on bench, pull dumbbell to hip. Drive elbow back and up. Trains horizontal pull unilaterally — addresses imbalances between sides.",
    muscle_groups: ["lats", "rhomboids", "biceps"],
  },
  {
    name: "Lat Pulldown",
    category: "pull",
    equipment: ["machine"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Pronated grip slightly wider than shoulders. Pull bar to upper chest, elbows drive down and back. Sit tall with a slight lean. Gateway to pull-ups — builds the lat strength needed for real world overhead function.",
    muscle_groups: ["lats", "biceps"],
  },
  {
    name: "Assisted Pull-Up",
    category: "pull",
    equipment: ["machine"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Machine-assisted pull-up. Full range of motion — dead hang to chin above bar. Goal is to reduce assistance session by session until bodyweight.",
    muscle_groups: ["lats", "biceps", "core"],
  },
  {
    name: "Pull-Up",
    category: "pull",
    equipment: ["bodyweight"],
    phase_unlock: 2,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Dead hang to chin above bar. Full range. One of the most reliable indicators of functional strength — if you can do 10 pull-ups at 80, you're doing something right.",
    muscle_groups: ["lats", "biceps", "core"],
  },

  // ── CARRY ──────────────────────────────────────────────
  {
    name: "Farmer's Walk",
    category: "carry",
    equipment: ["dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Heavy dumbbells in both hands, walk 20-30m. Shoulders packed down, chest up, brace the core. Dan John called this 'the perfect exercise' — simultaneously trains grip, core stability, posture, and conditioning.",
    muscle_groups: ["grip", "core", "traps", "glutes"],
  },
  {
    name: "Suitcase Carry",
    category: "carry",
    equipment: ["dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "One heavy dumbbell, keep body perfectly upright — fight the lean. 20-30m each side. Trains anti-lateral flexion, the core function most overlooked in traditional training.",
    muscle_groups: ["core", "grip", "obliques"],
  },

  // ── CORE ──────────────────────────────────────────────
  {
    name: "Pallof Press",
    category: "core",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Cable at chest height, perpendicular to your body. Press out and hold 2 seconds, resist rotation. Dr. McGill's go-to anti-rotation exercise. The spine is designed to resist movement, not create it.",
    muscle_groups: ["core", "obliques"],
  },
  {
    name: "Ab Wheel Rollout",
    category: "core",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Kneel, roll wheel forward until body is parallel to floor (or as far as you can maintain a neutral spine), roll back. One of the hardest anti-extension exercises. Start with short range — never let the lower back arch.",
    muscle_groups: ["core", "lats", "hip_flexors"],
  },
  {
    name: "Cable Crunch",
    category: "core",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Rope at cable tower overhead, kneel facing tower. Crunch elbows to knees, round the spine. The only weighted core flexion exercise — important to train the spine in all its functions, including flexion under load.",
    muscle_groups: ["core", "obliques"],
  },
  {
    name: "Dead Bug",
    category: "core",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Lie on back, arms and legs up. Slowly lower opposite arm and leg while pressing lower back into floor. Never let the back arch. The gold standard for lower back health — teaches spine neutral under limb loading.",
    muscle_groups: ["core", "lower_back"],
  },
  {
    name: "Bird Dog",
    category: "core",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "On hands and knees, extend opposite arm and leg simultaneously. Hold 3 seconds. One of Dr. McGill's Big 3 for spine health. Trains the entire posterior chain with zero spinal loading.",
    muscle_groups: ["core", "lower_back", "glutes"],
  },
  {
    name: "Side Plank",
    category: "core",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Side-lying position on forearm, hips up, body straight. Seconds are your target. Anti-lateral flexion — one of the most clinically important core functions for preventing lower back injury. Each side.",
    muscle_groups: ["obliques", "core", "glutes"],
  },
  {
    name: "Plank",
    category: "core",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Forearms on floor, body straight from head to heels. Squeeze glutes and brace the core — don't just hang there. Anti-extension. Reps = seconds held. 30-60 seconds is plenty if you're doing it right.",
    muscle_groups: ["core", "glutes", "lower_back"],
  },
  {
    name: "Hollow Body Hold",
    category: "core",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "On back, press lower back into floor, raise legs and arms. Full body tension — imagine being vacuum-sealed. Gymnastics-derived core stability. Reps = seconds held. Regress by bending knees.",
    muscle_groups: ["core", "hip_flexors"],
  },
  {
    name: "Superman Hold",
    category: "core",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Lie prone, arms extended. Lift chest, arms, and legs off the floor simultaneously. Hold at top. Trains the posterior chain in extension — counteracts the flexion of desk work and hip flexor dominance.",
    muscle_groups: ["lower_back", "glutes", "rear_delts"],
  },

  // ── SHOULDER HEALTH ──────────────────────────────────
  {
    name: "Cable Face Pull",
    category: "shoulder_health",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Rope attachment at face height. Pull to forehead, elbows high and flared wide, externally rotate at end range. Do these EVERY gym session without exception. The most important exercise for long-term shoulder health.",
    muscle_groups: ["rear_delts", "rotator_cuff", "traps"],
  },
  {
    name: "Band External Rotation",
    category: "shoulder_health",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Elbow pinned to side, rotate forearm outward against band resistance. Directly strengthens the rotator cuff external rotators. The external:internal rotation strength ratio (target ~2:3) is the best predictor of shoulder longevity.",
    muscle_groups: ["rotator_cuff", "rear_delts"],
  },
  {
    name: "Y-T-W on Incline Bench",
    category: "shoulder_health",
    equipment: ["dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Lie prone on incline bench with very light dumbbells. Form Y (arms overhead), T (arms out), W (elbows bent). 5-6 reps each letter without rest. Strengthens the scapular stabilizers that protect every pressing and pulling movement.",
    muscle_groups: ["rear_delts", "rotator_cuff", "rhomboids", "traps"],
  },
];

// ── STRETCHING EXERCISES ─────────────────────────────────
export const STRETCHING_EXERCISES = [
  // Hip & Lower Body
  { name: "Pigeon Pose", category: "hip", duration_sec: 75, description: "External hip rotation. Cross one ankle over opposite knee (lying) or full pigeon on mat. Hold without bouncing. Each side." },
  { name: "90/90 Hip Rotation", category: "hip", duration_sec: 60, description: "Sit with both knees at 90°. Rotate between internal and external hip positions. Best hip mobility drill." },
  { name: "Lizard Lunge", category: "hip", duration_sec: 60, description: "Low lunge with front foot outside hand. Sink hips forward. Deep hip flexor and groin stretch. Each side." },
  { name: "Figure Four Stretch", category: "hip", duration_sec: 60, description: "Lie on back, cross ankle over opposite knee, pull the knee toward chest. Targets piriformis and glutes. Each side." },
  { name: "Standing Forward Fold", category: "hamstrings", duration_sec: 60, description: "Feet hip-width, hinge forward, let head and arms hang. Bend knees slightly if needed. Release lower back and hamstrings." },
  { name: "Supine Hamstring Stretch", category: "hamstrings", duration_sec: 60, description: "Lie on back, pull one straight leg toward chest with hands. Keep lower back flat. Each side." },
  { name: "Low Lunge Hip Flexor", category: "hip_flexors", duration_sec: 60, description: "Back knee on floor, shift hips forward. Squeeze glute of the back leg to deepen. Essential for desk posture and lower back. Each side." },
  { name: "Dragon Lunge", category: "hip_flexors", duration_sec: 75, description: "Deep low lunge, both hands inside front foot. Sink hips low. One of the deepest hip flexor and groin openers. Each side." },
  // Thoracic & Upper Body
  { name: "Cat-Cow", category: "thoracic", duration_sec: 60, description: "On hands and knees. Arch back (cow), then round spine (cat). 10 slow reps. Inhale to arch, exhale to round. Wakes up the spine." },
  { name: "Thread the Needle", category: "thoracic", duration_sec: 60, description: "On hands and knees, slide one arm under body and rotate. Targets thoracic rotation — key for shoulder health. Each side." },
  { name: "Thoracic Rotation (seated)", category: "thoracic", duration_sec: 45, description: "Sit cross-legged, place hand behind head, rotate torso. Focus on mid-back movement, not lower back. Each side." },
  { name: "Doorframe Chest Stretch", category: "chest_shoulders", duration_sec: 45, description: "Forearm on doorframe at 90°, lean forward gently. Opens pec minor and front shoulder. Counteracts pushing movements. Each side." },
  { name: "Puppy Pose", category: "thoracic", duration_sec: 60, description: "On all fours, walk hands forward, lower chest to floor. Keep hips above knees. Stretches thoracic spine and lats." },
  { name: "Neck Side Stretch", category: "neck", duration_sec: 45, description: "Tilt ear to shoulder, use hand for very gentle pressure. Stretch traps and neck. Hold each side 20 sec." },
  { name: "Cross-Body Shoulder Stretch", category: "chest_shoulders", duration_sec: 45, description: "Pull one arm across chest with other hand. Rear delt and posterior shoulder stretch. Each side." },
  // Full Body & Simple
  { name: "Downward Dog", category: "full_body", duration_sec: 60, description: "Inverted V shape. Push floor away, lengthen spine, press heels toward floor. Stretches hamstrings, calves, lats, and shoulders simultaneously." },
  { name: "Child's Pose", category: "full_body", duration_sec: 60, description: "Sit back on heels, arms extended forward. Rest pose. Breathe into your lower back. Stretches lower back, hips, and shoulders gently." },
  { name: "Low Lunge with Reach", category: "full_body", duration_sec: 45, description: "Low lunge, reach same-side arm overhead and lean away. Opens hip flexor AND side body simultaneously. Each side." },
  // Core & Spine
  { name: "Cobra Pose", category: "spine", duration_sec: 45, description: "Lie prone, push chest up with arms. Keep elbows slightly bent. Breathe into the belly. Counteracts flexion — great for lower back." },
  { name: "Supine Spinal Twist", category: "spine", duration_sec: 60, description: "Lie on back, bring one knee across body. Rotate opposite direction with arm extended. Releases lower back and thoracic spine. Each side." },
  { name: "Glute Bridge Hold", category: "spine", duration_sec: 45, description: "Hip thrust position, hold at top for 45 sec. Squeeze glutes, breathe normally. Activates glutes and decompresses lower back." },
  { name: "Dead Bug Stretch", category: "spine", duration_sec: 45, description: "Lie on back, extend arms overhead and legs out while keeping lower back pressed down. Decompresses spine and opens thoracic." },
  // Yin / Deep
  { name: "Yin Pigeon (long hold)", category: "yin", duration_sec: 120, description: "Full pigeon pose, 2 minute hold. Allow tension to fully release. This is the most transformative hip exercise over time. Each side." },
  { name: "Saddle Pose", category: "yin", duration_sec: 90, description: "Sit between heels (or on block). Lean back on hands or elbows. Deep quad and hip flexor release. Come out slowly." },
  { name: "Supported Fish", category: "yin", duration_sec: 90, description: "Lie over a block or rolled blanket at mid-back. Arms out, heart opens. Thoracic extension and chest opener." },
  { name: "Banana Stretch", category: "yin", duration_sec: 75, description: "Lie on back, shift body into a C-shape. Side body and IT band stretch. Arms overhead. Hold each side." },
  // Mobility / Morning
  { name: "Hip Circles", category: "mobility", duration_sec: 30, description: "Standing, hands on hips, make large circles with pelvis. 10 each direction. Lubricates hip joints." },
  { name: "Shoulder Rolls", category: "mobility", duration_sec: 30, description: "Slow shoulder rolls forward and backward, 8 each direction. Releases tension and improves scapular movement." },
  { name: "Ankle Circles", category: "mobility", duration_sec: 30, description: "Seated or standing, trace large circles with each ankle. 10 each direction. Neglected but important for longevity." },
  { name: "Neck Rolls (half)", category: "mobility", duration_sec: 30, description: "Half-circle neck rolls ear to chest to other ear. Never full circles backward. Releases neck and upper trap tension." },
];

// ── STRETCHING ROUTINES ───────────────────────────────────
export const STRETCHING_ROUTINES = [
  {
    routine_number: 1,
    name: "Full Body Basics",
    focus: "Simple beginner-friendly holds covering the whole body",
    exercises: [
      "Child's Pose",
      "Cat-Cow",
      "Downward Dog",
      "Low Lunge Hip Flexor",
      "Figure Four Stretch",
      "Supine Hamstring Stretch",
      "Thread the Needle",
      "Doorframe Chest Stretch",
      "Standing Forward Fold",
      "Cobra Pose",
      "Supine Spinal Twist",
      "Child's Pose",
    ],
  },
  {
    routine_number: 2,
    name: "Hip Opening",
    focus: "Hip flexors, glutes, groin",
    exercises: [
      "Cat-Cow",
      "Hip Circles",
      "Low Lunge Hip Flexor",
      "Dragon Lunge",
      "Lizard Lunge",
      "Pigeon Pose",
      "90/90 Hip Rotation",
      "Figure Four Stretch",
      "Supine Hamstring Stretch",
      "Standing Forward Fold",
      "Supine Spinal Twist",
      "Child's Pose",
    ],
  },
  {
    routine_number: 3,
    name: "Upper Body & Thoracic",
    focus: "Shoulder health, upper back, neck",
    exercises: [
      "Neck Rolls (half)",
      "Shoulder Rolls",
      "Cat-Cow",
      "Thread the Needle",
      "Thoracic Rotation (seated)",
      "Puppy Pose",
      "Doorframe Chest Stretch",
      "Cross-Body Shoulder Stretch",
      "Neck Side Stretch",
      "Downward Dog",
      "Cobra Pose",
      "Child's Pose",
    ],
  },
  {
    routine_number: 4,
    name: "Morning Mobility",
    focus: "Gentle joint-by-joint wake-up",
    exercises: [
      "Neck Rolls (half)",
      "Shoulder Rolls",
      "Ankle Circles",
      "Hip Circles",
      "Cat-Cow",
      "Standing Forward Fold",
      "Low Lunge Hip Flexor",
      "Low Lunge with Reach",
      "Downward Dog",
      "Cobra Pose",
      "Supine Spinal Twist",
      "Child's Pose",
    ],
  },
  {
    routine_number: 5,
    name: "Deep Yin Recovery",
    focus: "Passive long holds for deep tissue release",
    exercises: [
      "Child's Pose",
      "Cat-Cow",
      "Dragon Lunge",
      "Yin Pigeon (long hold)",
      "Figure Four Stretch",
      "Saddle Pose",
      "Banana Stretch",
      "Supported Fish",
      "Supine Hamstring Stretch",
      "Supine Spinal Twist",
      "Standing Forward Fold",
      "Child's Pose",
    ],
  },
  {
    routine_number: 6,
    name: "Core & Spine",
    focus: "Spinal health and core flexibility",
    exercises: [
      "Cat-Cow",
      "Dead Bug Stretch",
      "Glute Bridge Hold",
      "Cobra Pose",
      "Child's Pose",
      "Thread the Needle",
      "Thoracic Rotation (seated)",
      "Supine Spinal Twist",
      "Supine Hamstring Stretch",
      "Standing Forward Fold",
      "Puppy Pose",
      "Child's Pose",
    ],
  },
];
