// ── EXERCISE LIBRARY ─────────────────────────────────────────────────────────
//
// Two flags decide where an exercise can appear, and neither is a hand-maintained
// gym/home duplicate — both derive from `equipment`:
//
//   Gym-eligible  — the equipment list contains genuinely loaded kit (dumbbell,
//                   barbell, cable, machine, kettlebell, medicine ball, belt, band).
//                   Push-ups, planks, jumps and ab-wheel work therefore never occupy
//                   a gym slot: there is no reason to travel to a gym to do them.
//   home_compatible — doable with a sturdy table, an ab wheel and bodyweight. That is
//                   the entire home inventory; there are no dumbbells at home.
//
// An exercise can be both. Bulgarian Split Squat is loaded with dumbbells at the gym
// and done bodyweight with the rear foot on a table at home — the same movement,
// meaningfully better with load, so it earns a place in each pool.

export const EXERCISES = [

  // ── HINGE ──────────────────────────────────────────────
  {
    name: "Dumbbell Romanian Deadlift",
    category: "hinge",
    equipment: ["dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Hip-hinge movement. Soft knees, push hips back, keep dumbbells close to legs. Feel the stretch in hamstrings at the bottom. THE foundational longevity exercise — trains the entire posterior chain.",
    muscle_groups: ["hamstrings", "glutes", "lower_back"],
  },
  {
    name: "Hip Thrust",
    category: "hinge",
    equipment: ["bodyweight", "dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Upper back on bench, drive hips up squeezing glutes hard at the top. Hold 1 second. Best glute-isolation exercise with minimal spinal loading.",
    muscle_groups: ["glutes", "hamstrings"],
  },
  {
    name: "Good Morning",
    category: "hinge",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Hands behind head, soft knees, hinge forward from hips until you feel hamstring tension. Drive hips forward to return. Teaches the hip-hinge pattern with no equipment.",
    muscle_groups: ["hamstrings", "glutes", "lower_back"],
  },
  {
    name: "Single Leg Glute Bridge",
    category: "hinge",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Lie on back, one foot on floor, other leg extended. Drive hips up through the grounded heel, squeeze glute at top. Builds unilateral hip strength and exposes asymmetries. Each side.",
    muscle_groups: ["glutes", "hamstrings", "core"],
  },
  {
    name: "Barbell Romanian Deadlift",
    category: "hinge",
    equipment: ["barbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Start standing (take the bar from the safety bars or Smith hooks). Soft knees, push the hips back and slide the bar down the thighs until the hamstrings are long and the back is still flat, then drive the hips through. Bar stays in contact with the legs. Hamstrings in the lengthened position, glutes, spinal erectors and bracing — the week's posterior-chain lift. Controlled reserve, never a grinder.",
    muscle_groups: ["hamstrings", "glutes", "lower_back"],
  },

  // ── SQUAT ──────────────────────────────────────────────
  {
    name: "Goblet Squat",
    category: "squat",
    equipment: ["dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Hold dumbbell at chest, feet shoulder-width, toes out slightly. Sit between knees, chest tall. The best teaching tool for the squat pattern — counterbalance keeps torso upright.",
    muscle_groups: ["quads", "glutes", "core"],
  },
  {
    name: "Bulgarian Split Squat",
    category: "squat",
    equipment: ["bodyweight", "dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Rear foot elevated on bench, front foot forward. Lower back knee toward floor with control. Research shows single-leg strength is the single best predictor of longevity outcomes. Each leg. At home, rest the rear foot on a sturdy table or chair and go bodyweight — it is hard enough without load.",
    muscle_groups: ["quads", "glutes", "hamstrings"],
  },
  {
    name: "Reverse Lunge",
    category: "squat",
    equipment: ["bodyweight", "dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Step backward, lower rear knee toward floor. Less knee stress than forward lunge. Keep front shin vertical and chest tall. Each side.",
    muscle_groups: ["quads", "glutes"],
  },
  {
    name: "Step Up",
    category: "squat",
    equipment: ["bodyweight", "trap_bar"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Bench at knee height or a little below. Load it by standing inside the open trap bar (start bodyweight until the pattern is solid). Whole foot on the bench, drive through the front heel — don't push off the back foot — stand tall, then lower under control. Unilateral strength, balance and hip/knee control. Reps are per leg.",
    muscle_groups: ["quads", "glutes"],
  },
  {
    name: "Barbell Back Squat",
    category: "squat",
    equipment: ["barbell"],
    phase_unlock: 3,
    shoulder_safe: false,
    lower_back_safe: true,
    home_compatible: false,
    description: "Bar on upper traps, brace hard, descend until thighs parallel. Requires shoulder mobility — Phase 3 only.",
    muscle_groups: ["quads", "glutes", "core"],
  },
  {
    name: "Trap Bar Deadlift",
    category: "hinge",
    equipment: ["trap_bar"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Stand inside a trap (hex) bar, neutral-grip handles at your sides. Brace, drive through the floor, stand tall, then control the descent. The shoulder-friendliest heavy leg lift — neutral grip and a centred load mean no bar on the back and less spinal shear than a conventional deadlift. Your heavy anchor lift. Keep it 3-5 strong reps — never grind to failure.",
    muscle_groups: ["glutes", "quads", "hamstrings", "lower_back", "grip"],
  },
  {
    name: "Safety Bar Squat",
    category: "squat",
    equipment: ["barbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Specialty bar with a padded yoke and front handles — no shoulder external rotation required, so it's far kinder to cranky shoulders than a back squat. The fallback heavy squat when the trap bar isn't available or a more upright squat pattern is wanted.",
    muscle_groups: ["quads", "glutes", "core"],
  },

  // ── PUSH ──────────────────────────────────────────────
  {
    name: "Dumbbell Floor Press",
    category: "push",
    equipment: ["dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Lie on floor, dumbbells at chest, press up. Floor limits shoulder extension at bottom — protects the joint. Great for learning pressing mechanics safely.",
    muscle_groups: ["chest", "triceps", "front_delts"],
  },
  {
    name: "Incline Dumbbell Press",
    category: "push",
    equipment: ["dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "30-45° incline bench. Press dumbbells from chest level, elbows at ~45° from body. Upper chest emphasis. More shoulder-friendly angle than flat pressing.",
    muscle_groups: ["upper_chest", "front_delts", "triceps"],
  },
  {
    name: "Push-Up",
    category: "push",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Hands shoulder-width, body straight line from head to heels. Lower chest to floor, press back up. The most complete upper-body bodyweight exercise. Scales infinitely — knees, standard, feet elevated, weighted vest.",
    muscle_groups: ["chest", "triceps", "front_delts", "core"],
  },
  {
    name: "Pike Push-Up",
    category: "push",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Inverted V position with hips high, head between arms. Lower crown of head toward floor and press back up. Trains the vertical push pattern and anterior deltoid without any equipment.",
    muscle_groups: ["front_delts", "triceps", "upper_chest"],
  },
  {
    name: "Incline Pike Push-Up",
    category: "push",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Hands on a chair seat, sofa arm or sturdy table, walk feet back and push hips up into a V, head between arms. Bend elbows to lower the crown of your head toward the surface, press back up. The accessible version of the pike push-up — far less inversion, no wrist/balance demands. Progress by using a lower surface until the floor version works.",
    muscle_groups: ["front_delts", "triceps", "upper_chest"],
  },
  {
    name: "Barbell Bench Press",
    category: "push",
    equipment: ["barbell"],
    phase_unlock: 2,
    shoulder_safe: false,
    lower_back_safe: true,
    home_compatible: false,
    description: "Flat bench, bar to lower chest. Phase 2+ only due to shoulder demands. Requires proper arch, leg drive, and shoulder positioning.",
    muscle_groups: ["chest", "triceps", "front_delts"],
  },
  {
    name: "Landmine Press",
    category: "push",
    equipment: ["barbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "One end of a barbell anchored in a landmine (or corner). Standing, both hands on the end of the bar at the upper chest, feet hip-width, glutes and trunk tight. Press up and forward along the arc to long arms, let the shoulder blades move with it, lower under control. The shoulder-friendliest vertical press: the arcing path avoids the impingement zone of strict overhead pressing. The primary heavy vertical press in this program — progress it like any main lift.",
    muscle_groups: ["front_delts", "upper_chest", "triceps", "core"],
  },
  {
    name: "Dumbbell Shoulder Press",
    category: "push",
    equipment: ["dumbbell"],
    phase_unlock: 2,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Seated, back supported, neutral or slightly-angled grip. Press dumbbells overhead without locking the shoulders up to the ears. True vertical pressing pattern — unlocked in Phase 2 once shoulder capacity is established. Stop short of any pinch; the landmine press is the regression if it bothers the shoulder.",
    muscle_groups: ["front_delts", "triceps", "upper_chest"],
  },

  // ── PULL ──────────────────────────────────────────────
  {
    name: "Chest Supported Row",
    category: "pull",
    equipment: ["cable", "bench"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Adjustable bench on a low incline, set facing the dual cable with both pulleys low. Chest on the pad, one handle in each hand, row to the lower ribs and drive the elbows back; pause, then lower under control. The chest pad takes the lower back out of it — hard upper-back volume without adding spinal load to a week that already has trap bar deadlifts and RDLs.",
    muscle_groups: ["lats", "rhomboids", "biceps", "rear_delts"],
  },
  {
    name: "Seated Cable Row",
    category: "pull",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Sit tall, neutral grip, pull to lower chest with elbows tight to body. Keep torso upright — don't rock. Trains the full lat and mid-back with constant tension.",
    muscle_groups: ["lats", "rhomboids", "biceps"],
  },
  {
    name: "Machine Row",
    category: "pull",
    equipment: ["machine"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Chest on pad, neutral grip handles. Pull to chest, squeeze shoulder blades together. Machine provides stability — ideal for focusing on the back without worrying about form elsewhere.",
    muscle_groups: ["lats", "rhomboids", "biceps"],
  },
  {
    name: "Dumbbell Single Arm Row",
    category: "pull",
    equipment: ["dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Knee and hand on bench, pull dumbbell to hip. Drive elbow back and up. Trains horizontal pull unilaterally — addresses imbalances between sides.",
    muscle_groups: ["lats", "rhomboids", "biceps"],
  },
  {
    name: "Lat Pulldown",
    category: "pull",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Lat bar on the high pulley, kneeling or seated on the bench in front of it. Grip slightly wider than the shoulders, pull the bar to the upper chest with the elbows driving down and back, sit tall with a slight lean. First rung of the vertical-pull ladder: pulldown → bodyweight pull-up → weighted pull-up.",
    muscle_groups: ["lats", "biceps"],
  },
  {
    name: "Assisted Pull-Up",
    category: "pull",
    equipment: ["machine"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Machine-assisted pull-up. Full range of motion — dead hang to chin above bar. Goal is to reduce assistance session by session until bodyweight.",
    muscle_groups: ["lats", "biceps", "core"],
  },
  {
    name: "Pull-Up",
    category: "pull",
    // The bar matters: this is bodyweight, but it needs gym kit. Tagged ["bodyweight"]
    // alone it was excluded from the gym pool by the loaded-equipment rule and could
    // never be selected — home has a table for rows, not a bar.
    equipment: ["bodyweight", "pull_up_bar"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Dead hang to chin above bar. Full range. One of the most reliable indicators of functional strength — if you can do 10 pull-ups at 80, you're doing something right.",
    muscle_groups: ["lats", "biceps", "core"],
  },
  {
    name: "Inverted Row",
    category: "pull",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Set the Smith bar at about hip height and lock it. Lie under it, grip just wider than the shoulders, body in a straight line from heels to head. Pull the chest to the bar, squeeze the shoulder blades together, lower with control. A true bodyweight horizontal pull with the shoulder blades free to move. Easier: raise the bar or walk the feet in. Harder: lower the bar, or put the heels up on the bench.",
    muscle_groups: ["lats", "rhomboids", "biceps", "rear_delts"],
  },

  // ── CARRY ──────────────────────────────────────────────
  {
    name: "Farmer's Walk",
    category: "carry",
    equipment: ["dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Heavy dumbbells in both hands, walk 20-30m. Shoulders packed down, chest up, brace the core. Dan John called this 'the perfect exercise' — simultaneously trains grip, core stability, posture, and conditioning.",
    muscle_groups: ["grip", "core", "traps", "glutes"],
  },
  {
    name: "Suitcase Carry",
    category: "carry",
    equipment: ["trap_bar"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "One side only, using the trap bar's single-handle (suitcase) setup. Pick it up like a one-arm deadlift, stand perfectly upright and walk; fight the lean and the rotation. 20-30 m per side. Log the total load of the bar and plates. Anti-lateral flexion, obliques, grip and unilateral loading.",
    muscle_groups: ["core", "grip", "obliques"],
  },

  // ── CORE ──────────────────────────────────────────────
  {
    name: "Pallof Press",
    category: "core",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Cable at chest height, perpendicular to your body. Press out and hold 2 seconds, resist rotation. Dr. McGill's go-to anti-rotation exercise. The spine is designed to resist movement, not create it.",
    muscle_groups: ["core", "obliques"],
  },
  {
    name: "Ab Wheel Rollout",
    category: "core",
    equipment: ["ab_wheel"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Kneel, roll wheel forward until body is parallel to floor (or as far as you can maintain a neutral spine), roll back. One of the hardest anti-extension exercises. Start with short range — never let the lower back arch.",
    muscle_groups: ["core", "lats", "hip_flexors"],
  },
  {
    name: "Cable Crunch",
    category: "core",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Rope at cable tower overhead, kneel facing tower. Crunch elbows to knees, round the spine. The only weighted core flexion exercise — important to train the spine in all its functions, including flexion under load.",
    muscle_groups: ["core", "obliques"],
  },
  {
    name: "Dead Bug",
    category: "core",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Lie on back, arms and legs up. Slowly lower opposite arm and leg while pressing lower back into floor. Never let the back arch. The gold standard for lower back health — teaches spine neutral under limb loading.",
    muscle_groups: ["core", "lower_back"],
  },
  {
    name: "Bird Dog",
    category: "core",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "On hands and knees, extend opposite arm and leg simultaneously. Hold 3 seconds. One of Dr. McGill's Big 3 for spine health. Trains the entire posterior chain with zero spinal loading.",
    muscle_groups: ["core", "lower_back", "glutes"],
  },
  {
    name: "Side Plank",
    category: "core",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Side-lying position on forearm, hips up, body straight. Seconds are your target. Anti-lateral flexion — one of the most clinically important core functions for preventing lower back injury. Each side.",
    muscle_groups: ["obliques", "core", "glutes"],
  },
  {
    name: "Plank",
    category: "core",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Forearms on floor, body straight from head to heels. Squeeze glutes and brace the core — don't just hang there. Anti-extension. Reps = seconds held. 30-60 seconds is plenty if you're doing it right.",
    muscle_groups: ["core", "glutes", "lower_back"],
  },
  {
    name: "Hollow Body Hold",
    category: "core",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "On back, press lower back into floor, raise legs and arms. Full body tension — imagine being vacuum-sealed. Gymnastics-derived core stability. Reps = seconds held. Regress by bending knees.",
    muscle_groups: ["core", "hip_flexors"],
  },
  {
    name: "Superman Hold",
    category: "core",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Lie prone, arms extended. Lift chest, arms, and legs off the floor simultaneously. Hold at top. Trains the posterior chain in extension — counteracts the flexion of desk work and hip flexor dominance.",
    muscle_groups: ["lower_back", "glutes", "rear_delts"],
  },

  // ── SHOULDER HEALTH ──────────────────────────────────
  {
    name: "Cable Face Pull",
    category: "shoulder_health",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Rope attachment at face height. Pull to forehead, elbows high and flared wide, externally rotate at end range. Do these EVERY gym session without exception. The most important exercise for long-term shoulder health.",
    muscle_groups: ["rear_delts", "rotator_cuff", "traps"],
  },
  {
    name: "Band External Rotation",
    category: "shoulder_health",
    // Needs a band, which the old ["bodyweight"] listing didn't say — that made it
    // ineligible for the gym pool AND unavailable at home, so it was unreachable.
    equipment: ["band"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Elbow pinned to side, rotate forearm outward against band resistance. Directly strengthens the rotator cuff external rotators. The external:internal rotation strength ratio (target ~2:3) is the best predictor of shoulder longevity.",
    muscle_groups: ["rotator_cuff", "rear_delts"],
  },
  {
    name: "Y-T-W on Incline Bench",
    category: "shoulder_health",
    equipment: ["dumbbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Lie prone on incline bench with very light dumbbells. Form Y (arms overhead), T (arms out), W (elbows bent). 5-6 reps each letter without rest. Strengthens the scapular stabilizers that protect every pressing and pulling movement.",
    muscle_groups: ["rear_delts", "rotator_cuff", "rhomboids", "traps"],
  },
  {
    name: "Prone Y-T-W (Floor)",
    category: "shoulder_health",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Lie face down, forehead resting on the floor. Raise the arms off the floor to form a Y (overhead), then a T (straight out to the sides), then a W (elbows bent, squeeze the shoulder blades down). 5-6 reps each letter, no weight needed. The no-equipment scapular-stabiliser drill that keeps the shoulders healthy on home days.",
    muscle_groups: ["rear_delts", "rotator_cuff", "rhomboids", "traps"],
  },

  // ── POWER ──────────────────────────────────────────────
  // Explosive, low-rep, low-fatigue work placed FIRST in the session so it's done
  // fresh. Power and fast-twitch fibres fade fastest with age — keeping them is one
  // of the highest-value longevity stimuli. Always explosive, full rest, NEVER to failure.
  {
    name: "Box Jump",
    category: "power",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Explosive two-foot jump onto a sturdy box, landing soft and quiet with bent knees. STEP down — never jump down. 3-5 reps with full rest between sets, always fresh and explosive, never to failure. Trains the fast-twitch power that fades fastest with age.",
    muscle_groups: ["glutes", "quads", "calves"],
  },
  {
    name: "Broad Jump",
    category: "power",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Explosive standing long jump for distance — swing the arms, jump forward, land soft on both feet with bent knees. 3-5 reps, full rest, always fresh and never to failure. Bodyweight horizontal power you can do anywhere.",
    muscle_groups: ["glutes", "quads", "hamstrings"],
  },
  {
    name: "Vertical Jump",
    category: "power",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Maximal vertical jump — reach for a target overhead, land soft with bent knees. 3-5 reps with full rest, always explosive and fresh, never to failure. Maintains lower-body power with zero equipment.",
    muscle_groups: ["glutes", "quads", "calves"],
  },
  {
    name: "Kettlebell Swing",
    category: "power",
    equipment: ["kettlebell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Explosive hip hinge — snap the hips to float the bell to chest height, arms relaxed, brace hard at the top. The hips do the work, never the arms or lower back. Powerful reps, never to failure; do it fresh, before the heavy lifting. Trains hip power and conditioning with low joint stress.",
    muscle_groups: ["glutes", "hamstrings", "core", "grip"],
  },
  {
    name: "Medicine Ball Slam",
    category: "power",
    equipment: ["medicine_ball"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Reach the ball overhead, then drive it into the floor with the whole body — hips, trunk and arms together. Full-body explosive output with no landing impact and no eccentric load, so it costs almost nothing to recover from. 3-5 hard reps, full rest, never a conditioning circuit.",
    muscle_groups: ["core", "lats", "glutes", "shoulders"],
  },
  {
    name: "Medicine Ball Rotational Throw",
    category: "power",
    equipment: ["medicine_ball"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Stand side-on to a wall, load the back hip, then throw the ball into the wall by rotating from the hips — arms just deliver what the hips produce. Rotational power is the most neglected athletic quality and the first to disappear; this trains it with almost no joint cost. Each side.",
    muscle_groups: ["obliques", "core", "glutes", "shoulders"],
  },

  // ── PHASE 2/3 UPGRADES ────────────────────────────────
  // Reachable only once the corresponding phase is selected. Before this rework
  // several of these existed in the library but no slot could ever pick them.
  {
    name: "Barbell Hip Thrust",
    category: "hinge",
    equipment: ["barbell"],
    phase_unlock: 2,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Upper back on a bench, barbell across the hips with a pad. Drive the hips up, squeeze hard at the top, hold a beat. The loaded progression of the dumbbell hip thrust — far more glute load with the spine still barely involved.",
    muscle_groups: ["glutes", "hamstrings"],
  },
  {
    name: "Cable Chest Press",
    category: "push",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Split stance, handles at chest height, press forward and slightly together. Constant tension through the whole range and a free path for the shoulder blades — kinder to a cranky shoulder than a fixed bar, and the cable keeps tension where dumbbells lose it at lockout.",
    muscle_groups: ["chest", "front_delts", "triceps", "core"],
  },
  {
    name: "Single Arm Cable Row",
    category: "pull",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Half-kneeling or split stance, one handle, row to the hip while resisting rotation. Unilateral pulling that exposes side-to-side differences and trains anti-rotation at the same time. Each side.",
    muscle_groups: ["lats", "rhomboids", "biceps", "core"],
  },
  {
    name: "Half-Kneeling Cable Pulldown",
    category: "pull",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Half-kneeling under a high pulley, pull the handle down to the shoulder with the elbow driving down and back. A vertical pull that doesn't require hanging bodyweight, so it's the accessible entry to overhead pulling strength. The half-kneeling stance stops the lower back arching to help.",
    muscle_groups: ["lats", "biceps", "core"],
  },
  {
    name: "Half-Kneeling Cable Chop",
    category: "core",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Half-kneeling, side-on to the cable set high. Pull the handle down and across the body with straight-ish arms, resisting the rotation the whole way. Anti-rotation under load — the trunk's most clinically relevant job, and one bodyweight work can't load properly. Each side.",
    muscle_groups: ["obliques", "core"],
  },
  {
    name: "Barbell Overhead Press",
    category: "push",
    equipment: ["barbell"],
    phase_unlock: 1,
    shoulder_safe: false,
    lower_back_safe: true,
    home_compatible: false,
    description: "Standing, bar taken from the safety bars at shoulder height. Press from the front rack to lockout overhead, head through at the top, ribs down and glutes tight so the lower back doesn't take the strain. Available as a swap for the Landmine Press. Stop the set the moment the shoulder pinches.",
    muscle_groups: ["front_delts", "triceps", "upper_chest", "core"],
  },
  {
    name: "Weighted Pull-Up",
    category: "pull",
    equipment: ["pull_up_bar", "plate"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Pull-ups with added load — a dip belt with a plate, or a plate held between the feet/ankles. Dead hang to chin over the bar, full control on the way down. Log only the ADDED weight. Last rung of the vertical-pull ladder: once bodyweight pull-ups hit the top of the rep range on every set, this is how vertical pulling keeps progressing.",
    muscle_groups: ["lats", "biceps", "core"],
  },

  // ── HOME PROGRESSIONS ─────────────────────────────────
  // Home has no load to add — a table, an ab wheel and bodyweight is the whole
  // inventory — so progression there is leverage, and the phase ladder IS the
  // progression rather than a bonus on top of it.
  {
    name: "Feet-Elevated Push-Up",
    category: "push",
    equipment: ["bodyweight"],
    phase_unlock: 2,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Push-up with the feet on a chair or table. Shifting weight forward puts noticeably more load on the chest and shoulders, and biases the upper chest. The first real step up from the standard push-up — keep the body in one line and don't let the hips sag.",
    muscle_groups: ["chest", "front_delts", "triceps", "core"],
  },
  {
    name: "Deficit Push-Up",
    category: "push",
    equipment: ["bodyweight"],
    phase_unlock: 3,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Hands on two books or low blocks so the chest descends below the hands. The extra range is where the difficulty comes from — go slowly at the bottom and stop short of any shoulder pinch. The hardest bodyweight horizontal press before one-arm work.",
    muscle_groups: ["chest", "front_delts", "triceps"],
  },
  {
    name: "Deficit Pike Push-Up",
    category: "push",
    equipment: ["bodyweight"],
    phase_unlock: 3,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Pike push-up with the hands elevated on books, or the feet on a table for a steeper angle. The closer the torso comes to vertical the closer this gets to a handstand press — the strongest vertical push available without any equipment.",
    muscle_groups: ["front_delts", "triceps", "upper_chest"],
  },
  {
    name: "Feet-Elevated Inverted Row",
    category: "pull",
    equipment: ["bodyweight"],
    phase_unlock: 2,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Inverted row under the table with the heels up on a chair, body horizontal. Raising the feet to torso height moves you toward pulling full bodyweight — the natural next step once standard inverted rows pass 12 clean reps.",
    muscle_groups: ["lats", "rhomboids", "biceps", "rear_delts"],
  },
  {
    name: "Archer Inverted Row",
    category: "pull",
    equipment: ["bodyweight"],
    phase_unlock: 3,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Inverted row pulling mainly with one arm while the other stays nearly straight out to the side. Shifts most of the load onto the working arm — the route toward a one-arm row when there is no way to add weight. Each side.",
    muscle_groups: ["lats", "rhomboids", "biceps", "core"],
  },
  {
    name: "Long-Lever Rollout",
    category: "core",
    equipment: ["ab_wheel"],
    phase_unlock: 2,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Ab wheel rollout starting from a taller kneeling position with the hips further forward, lengthening the lever. Considerably harder than the standard rollout. The rule doesn't change: the moment the lower back starts to arch, the set is over.",
    muscle_groups: ["core", "lats", "hip_flexors"],
  },
  {
    name: "Standing Rollout",
    category: "core",
    equipment: ["ab_wheel"],
    phase_unlock: 3,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Ab wheel rollout from standing, rolling out as far as a neutral spine allows and pulling back with the abs. One of the hardest anti-extension exercises there is. Build to it from a partial range against a wall — never let the lower back give way.",
    muscle_groups: ["core", "lats", "hip_flexors"],
  },
  {
    name: "Feet-Elevated Single Leg Glute Bridge",
    category: "hinge",
    equipment: ["bodyweight"],
    phase_unlock: 2,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Single leg glute bridge with the working heel up on a chair or table. The longer lever and greater hip range make it markedly harder than the floor version, and it brings the hamstring in alongside the glute. Each side.",
    muscle_groups: ["glutes", "hamstrings", "core"],
  },
  {
    name: "Nordic Hamstring Curl",
    category: "hinge",
    equipment: ["bodyweight"],
    phase_unlock: 3,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Kneel on a pad with the heels hooked under a loaded barbell on the floor (or the Smith bar locked at its lowest setting). Hips locked straight, lower the torso toward the floor as slowly as you can, then catch yourself with the hands and push back up. Progress by lowering further and slower, not by adding load. Among the best-evidenced exercises for reducing hamstring injury. Expect real soreness the first times — start with 1–2 sets of 3.",
    muscle_groups: ["hamstrings", "glutes", "core"],
  },
  {
    name: "Skater Squat",
    category: "squat",
    equipment: ["bodyweight"],
    phase_unlock: 3,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Single-leg squat with the rear leg trailing behind, lowering the back knee toward a cushion while the torso leans forward to counterbalance. Far more knee-friendly than a pistol squat and just as demanding. The hardest bodyweight single-leg pattern in the program. Each side.",
    muscle_groups: ["quads", "glutes", "hamstrings"],
  },
  {
    name: "Single-Leg Calf Raise",
    category: "calf",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Stand on one foot on a step with the heel hanging off, rise as high as possible, lower slowly under control. Calf strength and Achilles stiffness underpin walking speed and balance, both of which decline early and predict independence in old age — and running loads them hard. Each side.",
    muscle_groups: ["calves", "ankles"],
  },
  {
    name: "Plank with Shoulder Tap",
    category: "core",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "High plank, feet wide, tap the opposite shoulder with one hand while keeping the hips completely still. The anti-rotation work home training otherwise lacks — there is no cable at home for a Pallof press, and staying square here is the same job. Each tap is a rep.",
    muscle_groups: ["core", "obliques", "front_delts"],
  },

  // ── STRENGTH SYSTEM (Smith / cable / trap bar / medicine ball) ─────────────
  // The fixed Mon-Fri program in program-generator.ts is built on this kit: Smith
  // machine, dual cable, Olympic barbell + plates, open trap bar, adjustable bench,
  // pull-up station, landmine and one medicine ball. No dumbbells, no kettlebell.
  {
    name: "Countermovement Jump",
    category: "power",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Stand tall, dip fast into a quarter squat with an arm swing and jump straight up as high as possible. Land soft and quiet, reset fully between reps. Every rep maximal — stop the set if the height clearly drops. Vertical lower-body power, rate of force development and bone-loading impact.",
    muscle_groups: ["quads", "glutes", "calves"],
  },
  {
    name: "Smith Squat",
    category: "squat",
    equipment: ["smith"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Bar across the upper back, feet slightly in front of the bar, safeties set just below the bottom position. Brace, sit down between the heels to at least parallel, drive up. The fixed bar path lets you push the legs hard with less balance cost — heavy quad/glute work and bone loading with safe progression.",
    muscle_groups: ["quads", "glutes", "core"],
  },
  {
    name: "Smith Bulgarian Split Squat",
    category: "squat",
    equipment: ["smith", "bench"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Bar on the upper back, rear foot on the bench behind you, front foot far enough forward that the front shin stays fairly vertical at the bottom. Lower straight down until the back knee nearly touches, drive through the front foot. Unilateral quad/glute strength with side-to-side control. Reps are per leg — do the weaker side first.",
    muscle_groups: ["quads", "glutes", "adductors"],
  },
  {
    name: "Trap Bar Farmer Carry",
    category: "carry",
    equipment: ["trap_bar"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Deadlift the loaded trap bar, then walk 20-30 m with short, controlled steps. Shoulders packed, ribs down, no leaning, no swinging plates. Heavy but controlled — set it down before posture or grip breaks. Grip, traps, anti-lateral flexion and total-body robustness.",
    muscle_groups: ["grip", "traps", "core", "glutes"],
  },
  {
    name: "Smith Calf Raise",
    category: "calf",
    equipment: ["smith", "plate"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Bar on the upper back, balls of the feet on a plate or step so the heels can drop. Lower to a full stretch, pause, rise as high as possible, pause. Full range and controlled — no bouncing. Direct plantarflexion for calf and Achilles capacity.",
    muscle_groups: ["calves", "ankles"],
  },
  {
    name: "Smith Bench Press",
    category: "push",
    equipment: ["smith", "bench"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Flat bench under the Smith bar so it touches the lower chest, safeties set just above the chest. Shoulder blades pulled back and down, feet planted, lower under control, press. Primary horizontal pressing strength with a stable, safely progressed bar path.",
    muscle_groups: ["chest", "front_delts", "triceps"],
  },
  {
    name: "Smith Incline Bench Press",
    category: "push",
    equipment: ["smith", "bench"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Bench at roughly 30°, positioned so the bar meets the upper chest. Shoulder blades back and down, lower under control, press. Upper-chest hypertrophy work — reps in the 8-12 range, clean and controlled.",
    muscle_groups: ["upper_chest", "front_delts", "triceps"],
  },
  {
    name: "Cable Lateral Raise",
    category: "shoulder_health",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Low pulley, handle in the far hand, cable crossing in front of the body. Raise the arm out to the side to shoulder height with a slight elbow bend, lead with the elbow, lower slowly. Constant tension on the lateral deltoid. Reps are per side.",
    muscle_groups: ["side_delts"],
  },
  {
    name: "Smith Hip Thrust",
    category: "hinge",
    equipment: ["smith", "bench"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Upper back on the bench, Smith bar padded across the hips. Chin tucked, ribs down, drive the hips up until the torso is flat, squeeze the glutes for a beat, lower under control. Glute strength and hip extension with the spine barely loaded.",
    muscle_groups: ["glutes", "hamstrings"],
  },
  {
    name: "Cable Leg Curl",
    category: "hinge",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Ankle strap on the low pulley. Standing facing the stack (hands on the frame), or lying face-down on the bench with the strap on: curl the heel toward the glute without letting the hip move, lower slowly. If there is no ankle strap, loop a handle or rope around the ankle securely. Direct knee flexion for the hamstrings — the half the RDL doesn't train. Reps are per leg when done standing.",
    muscle_groups: ["hamstrings"],
  },
  {
    name: "Medicine Ball Chest Pass",
    category: "power",
    equipment: ["medicine_ball"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Stand facing a solid wall, ball at the chest. Step and throw it into the wall as fast as possible, extending the arms fully. Catch, reset, repeat. Maximal speed every rep — stop the set before the throws slow down. Upper-body horizontal power.",
    muscle_groups: ["chest", "triceps", "front_delts"],
  },
  {
    name: "Half-Kneeling Single-Arm Landmine Press",
    category: "push",
    equipment: ["barbell"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Half-kneeling, the knee on the pressing side down. Hold the end of the landmine bar at the shoulder in one hand, squeeze the glute of the down leg, ribs down, and press up and forward along the arc until the arm is long; let the shoulder blade move with it. Lower under control. One-sided, shoulder-friendly pressing with trunk anti-rotation. Reps are per side.",
    muscle_groups: ["front_delts", "upper_chest", "triceps", "serratus", "core"],
  },
  {
    name: "Cable External Rotation",
    category: "shoulder_health",
    equipment: ["cable"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Cable handle at elbow height, stand side-on with the working arm away from the stack. Elbow bent 90° and pinned to your side (a folded towel between elbow and ribs helps). Rotate the forearm outward, away from the body, pause, return slowly. Light and strict — the rotator cuff, not the whole body, does the work. Reps are per side.",
    muscle_groups: ["rotator_cuff", "rear_delts"],
  },
  {
    name: "Dead Hang",
    category: "pull",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: false,
    description: "Hang from the pull-up bar, overhand grip about shoulder width, arms straight. Keep the shoulders gently engaged — not shrugged up to the ears, not fully collapsed — and breathe slowly. Log the seconds held. Grip strength and the shoulders under a long, loaded stretch.",
    muscle_groups: ["grip", "lats", "shoulders"],
  },
  {
    name: "Single-Leg Romanian Deadlift",
    category: "hinge",
    equipment: ["bodyweight"],
    phase_unlock: 1,
    shoulder_safe: true,
    lower_back_safe: true,
    home_compatible: true,
    description: "Stand on one leg with a soft knee. Hinge at the hip, letting the free leg travel back in line with the torso, until the body is near horizontal or you lose position — hips stay square to the floor. Return slowly. A balance drill, not leg training: slow and steady, a fingertip on the rack is fine at first. Reps are per side.",
    muscle_groups: ["hamstrings", "glutes", "core"],
  },
];

// ── STRETCHING EXERCISES ─────────────────────────────────
export const STRETCHING_EXERCISES = [
  // Hip & Lower Body
  { name: "Pigeon Pose", category: "hip", duration_sec: 75, description: "External hip rotation. Cross one ankle over opposite knee (lying) or full pigeon on mat. Hold without bouncing. Each side." },
  { name: "90/90 Hip Rotation", category: "hip", duration_sec: 60, description: "Sit with both knees at 90°. Rotate between internal and external hip positions. Best hip mobility drill." },
  { name: "Lizard Lunge", category: "hip", duration_sec: 60, description: "Low lunge with front foot outside hand. Sink hips forward. Deep hip flexor and groin stretch. Each side." },
  { name: "Figure Four Stretch", category: "hip", duration_sec: 60, description: "Lie on back, cross ankle over opposite knee, pull the knee toward chest. Targets piriformis and glutes. Each side." },
  { name: "Standing Forward Fold", category: "hamstrings", duration_sec: 60, description: "Feet hip-width, hinge forward, let head and arms hang. Bend knees slightly if needed. Release lower back and hamstrings." },
  { name: "Supine Hamstring Stretch", category: "hamstrings", duration_sec: 60, description: "Lie on back, pull one straight leg toward chest with hands. Keep lower back flat. Each side." },
  { name: "Low Lunge Hip Flexor", category: "hip_flexors", duration_sec: 60, description: "Back knee on floor, shift hips forward. Squeeze glute of the back leg to deepen. Essential for desk posture and lower back. Each side." },
  { name: "Dragon Lunge", category: "hip_flexors", duration_sec: 75, description: "Deep low lunge, both hands inside front foot. Sink hips low. One of the deepest hip flexor and groin openers. Each side." },
  // Thoracic & Upper Body
  { name: "Cat-Cow", category: "thoracic", duration_sec: 60, description: "On hands and knees. Arch back (cow), then round spine (cat). 10 slow reps. Inhale to arch, exhale to round. Wakes up the spine." },
  { name: "Thread the Needle", category: "thoracic", duration_sec: 60, description: "On hands and knees, slide one arm under body and rotate. Targets thoracic rotation — key for shoulder health. Each side." },
  { name: "Thoracic Rotation (seated)", category: "thoracic", duration_sec: 45, description: "Sit cross-legged, place hand behind head, rotate torso. Focus on mid-back movement, not lower back. Each side." },
  { name: "Doorframe Chest Stretch", category: "chest_shoulders", duration_sec: 45, description: "Forearm on doorframe at 90°, lean forward gently. Opens pec minor and front shoulder. Counteracts pushing movements. Each side." },
  { name: "Puppy Pose", category: "thoracic", duration_sec: 60, description: "On all fours, walk hands forward, lower chest to floor. Keep hips above knees. Stretches thoracic spine and lats." },
  { name: "Neck Side Stretch", category: "neck", duration_sec: 45, description: "Tilt ear to shoulder, use hand for very gentle pressure. Stretch traps and neck. Hold each side 20 sec." },
  { name: "Cross-Body Shoulder Stretch", category: "chest_shoulders", duration_sec: 45, description: "Pull one arm across chest with other hand. Rear delt and posterior shoulder stretch. Each side." },
  // Full Body & Simple
  { name: "Downward Dog", category: "full_body", duration_sec: 60, description: "Inverted V shape. Push floor away, lengthen spine, press heels toward floor. Stretches hamstrings, calves, lats, and shoulders simultaneously." },
  { name: "Child's Pose", category: "full_body", duration_sec: 60, description: "Sit back on heels, arms extended forward. Rest pose. Breathe into your lower back. Stretches lower back, hips, and shoulders gently." },
  { name: "Low Lunge with Reach", category: "full_body", duration_sec: 45, description: "Low lunge, reach same-side arm overhead and lean away. Opens hip flexor AND side body simultaneously. Each side." },
  // Core & Spine
  { name: "Cobra Pose", category: "spine", duration_sec: 45, description: "Lie prone, push chest up with arms. Keep elbows slightly bent. Breathe into the belly. Counteracts flexion — great for lower back." },
  { name: "Supine Spinal Twist", category: "spine", duration_sec: 60, description: "Lie on back, bring one knee across body. Rotate opposite direction with arm extended. Releases lower back and thoracic spine. Each side." },
  { name: "Glute Bridge Hold", category: "spine", duration_sec: 45, description: "Hip thrust position, hold at top for 45 sec. Squeeze glutes, breathe normally. Activates glutes and decompresses lower back." },
  { name: "Dead Bug Stretch", category: "spine", duration_sec: 45, description: "Lie on back, extend arms overhead and legs out while keeping lower back pressed down. Decompresses spine and opens thoracic." },
  // Yin / Deep
  { name: "Yin Pigeon (long hold)", category: "yin", duration_sec: 120, description: "Full pigeon pose, 2 minute hold. Allow tension to fully release. This is the most transformative hip exercise over time. Each side." },
  { name: "Saddle Pose", category: "yin", duration_sec: 90, description: "Sit between heels (or on block). Lean back on hands or elbows. Deep quad and hip flexor release. Come out slowly." },
  { name: "Supported Fish", category: "yin", duration_sec: 90, description: "Lie over a block or rolled blanket at mid-back. Arms out, heart opens. Thoracic extension and chest opener." },
  { name: "Banana Stretch", category: "yin", duration_sec: 75, description: "Lie on back, shift body into a C-shape. Side body and IT band stretch. Arms overhead. Hold each side." },
  // Mobility / Morning
  { name: "Hip Circles", category: "mobility", duration_sec: 30, description: "Standing, hands on hips, make large circles with pelvis. 10 each direction. Lubricates hip joints." },
  { name: "Shoulder Rolls", category: "mobility", duration_sec: 30, description: "Slow shoulder rolls forward and backward, 8 each direction. Releases tension and improves scapular movement." },
  { name: "Ankle Circles", category: "mobility", duration_sec: 30, description: "Seated or standing, trace large circles with each ankle. 10 each direction. Neglected but important for longevity." },
  { name: "Neck Rolls (half)", category: "mobility", duration_sec: 30, description: "Half-circle neck rolls ear to chest to other ear. Never full circles backward. Releases neck and upper trap tension." },
  // Balance — single-leg balance is one of the strongest predictors of longevity.
  { name: "Single-Leg Stand", category: "balance", duration_sec: 30, description: "Stand on one leg, soft knee, eyes forward, stand tall and steady. 30 sec each leg. Single-leg balance is one of the strongest predictors of healthy ageing — train it like any other quality." },
  { name: "Single-Leg Stand (Eyes Closed)", category: "balance", duration_sec: 20, description: "Stand on one leg with eyes closed — removing vision forces the ankle, hip and inner ear to do the work. Stay near a wall for safety. 20 sec each leg. A big step up from the eyes-open version." },
  { name: "Single-Leg Balance with Head Turn", category: "balance", duration_sec: 25, description: "Balance on one leg and slowly turn the head side to side, then up and down. Challenges the vestibular system and balance together. 20-30 sec each leg, near a wall if needed." },
];

// ── STRETCHING ROUTINES ───────────────────────────────────
export const STRETCHING_ROUTINES = [
  {
    routine_number: 1,
    name: "Full Body Basics",
    focus: "Simple beginner-friendly holds covering the whole body",
    exercises: [
      "Child's Pose",
      "Cat-Cow",
      "Downward Dog",
      "Low Lunge Hip Flexor",
      "Figure Four Stretch",
      "Supine Hamstring Stretch",
      "Thread the Needle",
      "Doorframe Chest Stretch",
      "Standing Forward Fold",
      "Cobra Pose",
      "Supine Spinal Twist",
      "Child's Pose",
    ],
  },
  {
    routine_number: 2,
    name: "Hip Opening",
    focus: "Hip flexors, glutes, groin",
    exercises: [
      "Cat-Cow",
      "Hip Circles",
      "Single-Leg Balance with Head Turn",
      "Low Lunge Hip Flexor",
      "Dragon Lunge",
      "Lizard Lunge",
      "Pigeon Pose",
      "90/90 Hip Rotation",
      "Figure Four Stretch",
      "Supine Hamstring Stretch",
      "Standing Forward Fold",
      "Supine Spinal Twist",
      "Child's Pose",
    ],
  },
  {
    routine_number: 3,
    name: "Upper Body & Thoracic",
    focus: "Shoulder health, upper back, neck",
    exercises: [
      "Neck Rolls (half)",
      "Shoulder Rolls",
      "Single-Leg Stand (Eyes Closed)",
      "Cat-Cow",
      "Thread the Needle",
      "Thoracic Rotation (seated)",
      "Puppy Pose",
      "Doorframe Chest Stretch",
      "Cross-Body Shoulder Stretch",
      "Neck Side Stretch",
      "Downward Dog",
      "Cobra Pose",
      "Child's Pose",
    ],
  },
  {
    routine_number: 4,
    name: "Morning Mobility",
    focus: "Gentle joint-by-joint wake-up",
    exercises: [
      "Neck Rolls (half)",
      "Shoulder Rolls",
      "Ankle Circles",
      "Hip Circles",
      "Single-Leg Stand",
      "Cat-Cow",
      "Standing Forward Fold",
      "Low Lunge Hip Flexor",
      "Low Lunge with Reach",
      "Downward Dog",
      "Cobra Pose",
      "Supine Spinal Twist",
      "Child's Pose",
    ],
  },
  {
    routine_number: 5,
    name: "Deep Yin Recovery",
    focus: "Passive long holds for deep tissue release",
    exercises: [
      "Child's Pose",
      "Cat-Cow",
      "Dragon Lunge",
      "Yin Pigeon (long hold)",
      "Figure Four Stretch",
      "Saddle Pose",
      "Banana Stretch",
      "Supported Fish",
      "Supine Hamstring Stretch",
      "Supine Spinal Twist",
      "Standing Forward Fold",
      "Child's Pose",
    ],
  },
  {
    routine_number: 6,
    name: "Core & Spine",
    focus: "Spinal health and core flexibility",
    exercises: [
      "Cat-Cow",
      "Dead Bug Stretch",
      "Glute Bridge Hold",
      "Cobra Pose",
      "Child's Pose",
      "Thread the Needle",
      "Thoracic Rotation (seated)",
      "Supine Spinal Twist",
      "Supine Hamstring Stretch",
      "Standing Forward Fold",
      "Puppy Pose",
      "Child's Pose",
    ],
  },
];
